# base directories
category_to_p_images_fp: "/home/cs-shin1/datasets/ImageNet2012/coco2017_category_to_p_images_n500.json"
dir_ckpt: "/home/cs-shin1/namedmask/ckpt"
dir_train_dataset: "/home/cs-shin1/datasets/ImageNet2012"
dir_val_dataset: "/home/cs-shin1/datasets/coco2017"

# augmentations
max_n_masks: 2
scale_range: [ 0.1, 1.0 ]

use_expert_pseudo_masks: true
category_agnostic: false

n_categories: 81
categories: [
    'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
    'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant',
    'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard',
    'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle',
    'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli',
    'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet',
    'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator',
    'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush'
]
n_images: 500

# dataset
dataset_name: "coco2017"
split: "val"
train_image_size: 384

# dataloader:
train_dataloader_kwargs:
  batch_size: 16
  num_workers: 16
  pin_memory: true
  shuffle: true

val_dataloader_kwargs:
  batch_size: 1
  num_workers: 4
  pin_memory: true

# Segmenter configuration
# ["deeplabv3plus_resnet101", "deeplabv3plus_resnet50", "deeplabv3plus_mobilenet"]
segmenter_name: "deeplabv3plus_resnet50"

# optimiser
lr: 0.0005
momentum: 0.9
weight_decay: 0.0002
betas: [0.9, 0.999]
n_iters: 20000

iter_eval: 1000
iter_log: 100
